#define DEVICE_ID "1"

#define IN_TOPIC "/in"
#define OUT_TOPIC "/out"
#define STATUS_TOPIC "/status"
#define TEMPERATURE_TOPIC "/temperature"
#define TOPICS_ROOT "makerfabs/hvacremote/"

#define MY_MQTT_IN_TOPIC TOPICS_ROOT DEVICE_ID IN_TOPIC
#define MY_MQTT_OUT_TOPIC TOPICS_ROOT DEVICE_ID OUT_TOPIC
#define MY_MQTT_STATUS_TOPIC TOPICS_ROOT DEVICE_ID STATUS_TOPIC
#define MY_MQTT_TEMPERATURE_TOPIC TOPICS_ROOT DEVICE_ID TEMPERATURE_TOPIC
#define MQTT_BUFFER_LENGTH 300
#define MQTT_STATUS_UPDATE_TIME_MS 60000
#define MQTT_MAX_RETRIES 6