// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: 7_5_23

#ifndef _7_5_23_UI_H
#define _7_5_23_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
    // SCREEN: ui_Screen1
    void ui_Screen1_screen_init(void);
    void ui_event_Screen1(lv_event_t *e);
    extern lv_obj_t *ui_Screen1;
    void ui_event_Slider2(lv_event_t *e);
    extern lv_obj_t *ui_Slider2;
    extern lv_obj_t *ui_Label2;
    void ui_event_Switch1(lv_event_t *e);
    extern lv_obj_t *ui_Switch1;
    extern lv_obj_t *ui_Label4;
    void ui_event_Dropdown2(lv_event_t *e);
    extern lv_obj_t *ui_Dropdown2;
    void ui_event_Switch2(lv_event_t *e);
    extern lv_obj_t *ui_Switch2;
    void ui_event_Switch3(lv_event_t *e);
    extern lv_obj_t *ui_Switch3;
    extern lv_obj_t *ui_Label1;
    extern lv_obj_t *ui_Label3;
    extern lv_obj_t *ui_Image1;
    extern lv_obj_t *ui_Image2;
    extern lv_obj_t *ui_Image3;
    extern lv_obj_t *ui_Image4;
    extern lv_obj_t *ui_Label6;
    extern lv_obj_t *ui_Label7;
    // SCREEN: ui_Screen2
    void ui_Screen2_screen_init(void);
    void ui_event_Screen2(lv_event_t *e);
    extern lv_obj_t *ui_Screen2;
    // SCREEN: ui_Screen3
    void ui_Screen3_screen_init(void);
    void ui_event_Screen3(lv_event_t *e);
    extern lv_obj_t *ui_Screen3;
    void ui_event_Button2(lv_event_t *e);
    extern lv_obj_t *ui_Button2;
    extern lv_obj_t *ui_Label9;
    void ui_event_Label8(lv_event_t * e);
    extern lv_obj_t *ui_Label8;
    // SCREEN: ui_Screen4
    void ui_Screen4_screen_init(void);
    void ui_event_Screen4(lv_event_t * e);
    extern lv_obj_t * ui_Screen4;
    void ui_event_Label10(lv_event_t * e);
    extern lv_obj_t * ui_Label10;
    extern lv_obj_t * ui____initial_actions0;
    extern lv_obj_t *ui____initial_actions0;

    LV_IMG_DECLARE(ui_img_bw_arrow_png); // assets\bw_arrow.png

    LV_FONT_DECLARE(ui_font_MMBold24);
    LV_FONT_DECLARE(ui_font_MMMedium24);
    LV_FONT_DECLARE(ui_font_MMRegular24);

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
