// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: 7_5_23

#include "ui.h"

void ui_door_screen_screen_init(void)
{
    ui_door_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_door_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_door_button = lv_btn_create(ui_door_screen);
    lv_obj_set_width(ui_door_button, 100);
    lv_obj_set_height(ui_door_button, 50);
    lv_obj_set_x(ui_door_button, 0);
    lv_obj_set_y(ui_door_button, 50);
    lv_obj_set_align(ui_door_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_door_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_door_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_door_button_label = lv_label_create(ui_door_button);
    lv_obj_set_width(ui_door_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_door_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_door_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_door_button_label, "OK");
    lv_obj_set_style_text_font(ui_door_button_label, &ui_font_MMBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_door_label = lv_label_create(ui_door_screen);
    lv_obj_set_width(ui_door_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_door_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_door_label, 0);
    lv_obj_set_y(ui_door_label, -20);
    lv_obj_set_align(ui_door_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_door_label, "The mini-split was turned off\nbecause the door was left open.");
    lv_obj_add_flag(ui_door_label, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_door_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_door_label, &ui_font_MMBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_door_button, ui_event_door_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_door_label, ui_event_door_label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_door_screen, ui_event_door_screen, LV_EVENT_ALL, NULL);

}
