// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: 7_5_23

#include "ui.h"
#include <Arduino.h>

void display_slider_checked(lv_event_t * e)
{
	Serial.println("Display on");
}

void display_slider_unchecked(lv_event_t * e)
{
	Serial.println("Display off");
}

void boost_slider_checked(lv_event_t * e)
{
	Serial.println("Boost on");
}

void boost_slider_unchecked(lv_event_t * e)
{
	Serial.println("Boost off");
}

void mode_changed(lv_event_t * e)
{
	char buf[32];
	lv_dropdown_get_selected_str(e->target, buf, sizeof(buf));
	Serial.println(buf);
}

void slider_released(lv_event_t * e)
{	
	int32_t value = lv_slider_get_value(e->target);
	Serial.print("Set point changed to ");
	Serial.println(value);
}

void swing_vert_slider_checked(lv_event_t * e)
{
	Serial.println("Vertical swing on");
}

void swing_vert_slider_unchecked(lv_event_t * e)
{
	Serial.println("Vertical swing off");
}

void swing_horz_checked(lv_event_t * e)
{
	Serial.println("Horizontal swing on");
}

void swing_horz_unchecked(lv_event_t * e)
{
	Serial.println("Horizontal swing off");
}
