// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: 7_5_23

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void slider_released(lv_event_t * e);
void boost_slider_checked(lv_event_t * e);
void boost_slider_unchecked(lv_event_t * e);
void mode_changed(lv_event_t * e);
void swing_vert_slider_checked(lv_event_t * e);
void swing_vert_slider_unchecked(lv_event_t * e);
void swing_horz_checked(lv_event_t * e);
void swing_horz_unchecked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
