// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: 7_5_23

#include "../ui.h"

void ui_blank_screen_screen_init(void)
{
    ui_blank_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_blank_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_blank_screen, ui_event_blank_screen, LV_EVENT_ALL, NULL);

}
