// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: 7_5_23

#ifndef _7_5_23_UI_H
#define _7_5_23_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_main_screen
void ui_main_screen_screen_init(void);
void ui_event_main_screen(lv_event_t * e);
extern lv_obj_t * ui_main_screen;
void ui_event_main_slider(lv_event_t * e);
extern lv_obj_t * ui_main_slider;
extern lv_obj_t * ui_target_temp_label;
void ui_event_boost_switch(lv_event_t * e);
extern lv_obj_t * ui_boost_switch;
extern lv_obj_t * ui_boost_label;
void ui_event_mode_dropdown(lv_event_t * e);
extern lv_obj_t * ui_mode_dropdown;
void ui_event_fan_vert_switch(lv_event_t * e);
extern lv_obj_t * ui_fan_vert_switch;
void ui_event_fan_horz_switch(lv_event_t * e);
extern lv_obj_t * ui_fan_horz_switch;
extern lv_obj_t * ui_fan_vert_label;
extern lv_obj_t * ui_fan_horz_label;
extern lv_obj_t * ui_arrow_up_image;
extern lv_obj_t * ui_arrow_down_image;
extern lv_obj_t * ui_arrow_right_image;
extern lv_obj_t * ui_arrow_left_image;
extern lv_obj_t * ui_mode_label;
extern lv_obj_t * ui_room_temp_label;
extern lv_obj_t * ui_thermostat_temp_label;
// SCREEN: ui_blank_screen
void ui_blank_screen_screen_init(void);
void ui_event_blank_screen(lv_event_t * e);
extern lv_obj_t * ui_blank_screen;
// SCREEN: ui_door_screen
void ui_door_screen_screen_init(void);
void ui_event_door_screen(lv_event_t * e);
extern lv_obj_t * ui_door_screen;
void ui_event_door_button(lv_event_t * e);
extern lv_obj_t * ui_door_button;
extern lv_obj_t * ui_door_button_label;
void ui_event_door_label(lv_event_t * e);
extern lv_obj_t * ui_door_label;
// SCREEN: ui_reconnect_screen
void ui_reconnect_screen_screen_init(void);
void ui_event_reconnect_screen(lv_event_t * e);
extern lv_obj_t * ui_reconnect_screen;
void ui_event_reconnect_label(lv_event_t * e);
extern lv_obj_t * ui_reconnect_label;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bw_arrow_png);    // assets\bw_arrow.png

LV_FONT_DECLARE(ui_font_MMBold24);
LV_FONT_DECLARE(ui_font_MMMedium24);
LV_FONT_DECLARE(ui_font_MMRegular24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
