// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: 7_5_23

#include "ui.h"

void screen_clicked(lv_event_t * e)
{
	// Your code here
}

void slider_released(lv_event_t * e)
{
	// Your code here
}

void boost_slider_checked(lv_event_t * e)
{
	// Your code here
}

void boost_slider_unchecked(lv_event_t * e)
{
	// Your code here
}

void mode_changed(lv_event_t * e)
{
	// Your code here
}

void swing_vert_slider_checked(lv_event_t * e)
{
	// Your code here
}

void swing_vert_slider_unchecked(lv_event_t * e)
{
	// Your code here
}

void swing_horz_checked(lv_event_t * e)
{
	// Your code here
}

void swing_horz_unchecked(lv_event_t * e)
{
	// Your code here
}
